import {db,doc,getDoc,getDocs,collection,addDoc,updateDoc,serverTimestamp} from "./firebase.js";
const q=s=>document.querySelector(s),esc=s=>String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
let institution=null,account=null,permission=false,settings=null,terms=[],programs=[],records=[],offerings=[],tab="setup";
async function read(n){try{let s=await getDocs(collection(db,"institutions",institution.id,n));return s.docs.map(d=>({id:d.id,...d.data()}));}catch(e){console.warn(n,e);return [];}}
const button=(name,action)=>'<button class="secondary-btn small-btn" data-campus-action="'+action+'">'+name+'</button>';
const input=(name,label,type="text")=>'<label>'+label+'<input name="'+name+'" type="'+type+'" required maxlength="150"></label>';
const select=(name,label,opts)=>'<label>'+label+'<select name="'+name+'">'+opts.map(([v,n])=>'<option value="'+esc(v)+'">'+esc(n)+'</option>').join("")+'</select></label>';
const list=(array,format)=>array.length?'<div class="school-list">'+array.map(x=>'<div class="school-entry">'+format(x)+'</div>').join("")+'</div>':'<p class="school-empty">No records yet.</p>';
async function load(){if(!permission)return;let id=institution.id;let result=await Promise.all([getDoc(doc(db,"institutions",id,"configuration","general")),...["terms","academicPrograms","studentRecords","offerings"].map(read)]);if(institution.id!==id)return;settings=result[0].exists()?result[0].data():null;[terms,programs,records,offerings]=result.slice(1);render();}
function render(){const el=q("#campusOperations");if(!el)return;if(!permission){el.innerHTML="";return;}
el.innerHTML='<section class="school-admin"><div class="eyebrow">Academic Structure</div><h2>College & High School Operations</h2><div class="school-admin-tabs">'+[["setup","School configuration"],["credits","Credit audit"],["catalog","Catalog & terms"]].map(([x,t])=>'<button class="'+(tab===x?"selected":"")+'" data-campus-tab="'+x+'">'+t+'</button>').join("")+'</div><div id="campusContent">'+body()+'</div></section>';}
function body(){if(tab==="setup")return '<div class="school-section-head"><h3>Institution academic model</h3>'+button(settings?"Update settings":"Configure institution","settings")+'</div><p>Choose policies for secondary or postsecondary instruction without modifying existing courses.</p>'+list(settings?[settings]:[],s=>'<strong>'+esc(s.level==="college"?"College / University":s.level==="high_school"?"High School":"Mixed institution")+'</strong><span>Credit system: '+esc(s.creditSystem)+' · Academic calendar: '+esc(s.calendarSystem)+' · GPA scale: '+esc(s.gpaScale)+'</span>');
if(tab==="credits"){
 const certified=records.filter(r=>r.status==="certified");
 const grouped=new Map();
 for(const record of certified){const key=record.studentUid||"unknown";const prev=grouped.get(key)||{name:record.studentName||key,total:0,count:0};prev.total+=Number(record.credits)||0;prev.count++;grouped.set(key,prev);}
 const students=[...grouped.values()].sort((a,b)=>a.name.localeCompare(b.name));
 const gradePoints={"A+":4,"A":4,"A-":3.7,"B+":3.3,"B":3,"B-":2.7,"C+":2.3,"C":2,"C-":1.7,"D+":1.3,"D":1,"D-":0.7,"F":0};
 const gpas=new Map();
 for(const record of certified){const uid=record.studentUid||"unknown";const grade=String(record.finalGrade||"").trim().toUpperCase();if(!(grade in gradePoints))continue;const credits=Number(record.credits);if(!Number.isFinite(credits)||credits<=0)continue;const prev=gpas.get(uid)||{points:0,credits:0};prev.points+=credits*gradePoints[grade];prev.credits+=credits;gpas.set(uid,prev);}
 for(const student of students){const uid=certified.find(r=>(r.studentName||r.studentUid)===student.name)?.studentUid;const gpa=gpas.get(uid);student.gpa=gpa?.credits?(gpa.points/gpa.credits).toFixed(2):"N/A";}
 const total=certified.reduce((n,r)=>n+(Number(r.credits)||0),0);
 return '<h3>Certified credits by student</h3><p class="school-subtle">Advisory totals reflect institution-entered certified records only. Validate transfer credits, repeated courses, degree applicability, course equivalency, and transcript accuracy before certifying graduation.</p><div class="school-metrics"><div><strong>'+certified.length+'</strong><span>Certified records</span></div><div><strong>'+students.length+'</strong><span>Students represented</span></div><div><strong>'+total.toFixed(1)+'</strong><span>Credits across all students</span></div></div>'+
 (students.length?'<div class="school-list">'+students.map(s=>'<div class="school-entry"><strong>'+esc(s.name)+'</strong><span>'+s.total.toFixed(1)+' recorded credits · '+s.count+' certified course attempts</span></div>').join("")+'</div>':'<p class="school-empty">No certified student records are available yet.</p>')+
 '<h3>Academic program requirements</h3>'+list(programs,p=>'<strong>'+esc(p.name)+'</strong><span>'+esc(p.credits)+' required credits · '+esc(p.description)+'</span>');
}
return '<h3>Catalog offerings</h3>'+list(offerings,o=>'<strong>'+esc(o.title)+'</strong><span>'+esc(o.term)+' · '+esc(o.code)+' · '+esc(o.period||"Unscheduled")+'</span>')+'<h3>Academic terms</h3>'+list(terms,t=>'<strong>'+esc(t.title)+'</strong><span>'+esc(t.startDate)+' — '+esc(t.endDate)+'</span>');
}
function form(title,fields,save){let root=q("#modalRoot");root.innerHTML='<div class="modal-backdrop institution-modal-backdrop"><div class="modal institution-dialog" role="dialog" aria-modal="true"><div class="modal-header"><h2>'+esc(title)+'</h2><button type="button" class="secondary-btn" id="campusClose">Close</button></div><form id="campusForm" class="institution-form">'+fields+'<p id="campusError" role="alert"></p><button class="primary-btn" type="submit">Save configuration</button></form></div></div>';q("#campusClose").onclick=()=>root.innerHTML="";q("#campusForm").onsubmit=async event=>{event.preventDefault();const btn=event.currentTarget.querySelector("button[type=submit]");btn.disabled=true;try{await save(new FormData(event.currentTarget));root.innerHTML="";await load();}catch(e){q("#campusError").textContent=e.message;btn.disabled=false;}};}
function edit(){form("Institution academic settings",select("level","Institution level",[["high_school","High School"],["college","College / University"],["mixed","Mixed / Independent"]])+select("creditSystem","Credit unit",[["carnegie","Carnegie unit"],["semester","Semester credit hours"],["quarter","Quarter credit hours"]])+select("calendarSystem","Academic calendar",[["semester","Semesters"],["trimester","Trimesters"],["quarter","Quarters"]])+select("gpaScale","GPA scale",[["4","4.0"],["5","5.0 weighted"]]),async f=>{await updateOrCreate({...Object.fromEntries(f.entries()),updatedBy:account.uid,updatedAt:serverTimestamp()});});let fields=q("#campusForm").elements;if(settings)for(let k of ["level","creditSystem","calendarSystem","gpaScale"])fields[k].value=settings[k];}
async function updateOrCreate(record){const ref=doc(db,"institutions",institution.id,"configuration","general");const snap=await getDoc(ref);if(snap.exists())await updateDoc(ref,record);else{const {setDoc}=await import("./firebase.js");await setDoc(ref,record);}}
document.addEventListener("click",event=>{const page=event.target.closest("[data-campus-tab]");if(page){tab=page.dataset.campusTab;render();}const action=event.target.closest("[data-campus-action]");if(action?.dataset.campusAction==="settings")edit();});
window.TheoriaCampus={mount:async(inst,me)=>{institution=inst;account=me;permission=inst.ownerUid===me.uid;if(!permission){try{let m=await getDoc(doc(db,"institutions",inst.id,"staff",me.uid));permission=m.exists()&&["principal","assistant_principal","district_admin","registrar"].includes(m.data().role);}catch(e){permission=false;}}load().catch(console.error);}};
